import {
  User,
  Mail,
  Phone,
  House,
  Shield,
  Clock,
  AlertTriangle,
  CheckCircle,
} from "lucide-react";

// PERDORNAL INFORMATION FOR THE PTOPOFILE PAGE
export const persornalinformation = () => [
  {
    id: 1,
    label: "Full Name",
    name: "Sarah Anderson",
    icon: <User />,
  },
  {
    id: 2,
    label: "Email Address",
    email: "sarah.andrerson@cc.gov",
    icon: <Mail />,
  },
  {
    id: 3,
    label: "Phone Number",
    phone: +2348034567890,
    icon: <Phone />,
  },
  {
    id: 4,
    label: "Departmentmber",
    deprtment: "Internal Audit Division",
    icon: <House />,
  },
  {
    id: 5,
    label: "Role",
    role: "Senior Auditor",
    icon: <Shield />,
  },
];

// RECENT ACTIVITY FOR THE PROFILE PAGE
export const Recent = () => [
  {
    id: 1,
    name: "Reviewed Case ACC-2847",
    icon: <Clock />,
    time: "2 hours ago",
  },
  {
    id: 2,
    name: "Generated monthly report",
    icon: <Clock />,
    time: "5 hours ago",
  },
  {
    id: 3,
    name: "Updated case evidence ACC-1923",
    icon: <Clock />,
    time: "yesterday, 3:45 PM",
  },
  {
    id: 4,
    name: "Closed investigation ACC-5621",
    icon: <Clock />,
    time: "yesterday, 11:20 AM",
  },
  {
    id: 4,
    name: "Created new alert ACC-7634",
    icon: <Clock />,
    time: "2 days ago",
  },
];

// EMPLOYEE INFORMATION FOR THE EMPLOYEE RECORDS PAGE
export const employees = [
  {
    name: "Maria Amos",
    id: "EMP-2024-001",
    department: "Finance Department",
    role: "Accountant",
    bank: "**** **** **** 4892",
    risk: "Duplicate Account",
    severity: "Critical",
    status: "Flagged",
    icon: <AlertTriangle size={12} />,
  },
  {
    name: "Robert Marry",
    id: "EMP-2022-042",
    department: "Operations",
    role: "Operations Manager",
    bank: "**** **** **** 5678",
    risk: "Ghost Employee",
    severity: "Medium",
    status: "Verified",
    icon: <CheckCircle size={12} />,
  },
  {
    name: "John Chkwus",
    id: "EMP-2022-043",
    department: "IT Department",
    role: "Software Engineer",
    bank: "**** **** **** 5678",
    risk: "Duplicate Account",
    severity: "High",
    status: "flagged",
    icon: <AlertTriangle size={12}/>,
  },
  {
    name: "Robert Marry",
    id: "EMP-2022-044",
    department: "Operations",
    role: "Operations Manager",
    bank: "**** **** **** 5678",
    info: "Shared with 4 other employees",
    risk: "Ghost Employee",
    severity: "Medium",
    status: "Verified",
    icon: <CheckCircle size={12} />,
  },
  {
    name: "Robert Marry",
    id: "EMP-2022-045",
    department: "Operations",
    role: "Operations Manager",
    bank: "**** **** **** 5678",
    risk: "Ghost Employee",
    severity: "Medium",
    status: "flagged",
    icon: <AlertTriangle size={12} />,
  },
  {
    name: "Robert Marry",
    id: "EMP-2022-046",
    department: "Operations",
    role: "Operations Manager",
    bank: "**** **** **** 5678",
    info: "Shared with 4 other employees",
    risk: "Ghost Employee",
    severity: "Critical",
    status: "Verified",
    icon: <CheckCircle size={12} />,
  },
  {
    name: "Robert Marry",
    id: "EMP-2022-047",
    department: "Operations",
    role: "Operations Manager",
    bank: "**** **** **** 5678",
    risk: "Ghost Employee",
    severity: "Medium",
    status: "Verified",
    icon: <CheckCircle size={12} />,
  },
  {
    name: "Robert Marry",
    id: "EMP-2022-048",
    department: "Operations",
    role: "Operations Manager",
    bank: "**** **** **** 5678",
    info: "Shared with 4 other employees",
    risk: "Ghost Employee",
    severity: "Critical",
    status: "flagged",
    icon: <AlertTriangle size={12} />,
  },
  {
    name: "Robert Marry",
    id: "EMP-2022-049",
    department: "Operations",
    role: "Operations Manager",
    bank: "**** **** **** 5678",
    info: "Shared with 4 other employees",
    risk: "Ghost Employee",
    severity: "High",
    status: "flagged",
    icon: <AlertTriangle size={12} />,
  },
  {
    name: "Robert Marry",
    id: "EMP-2022-0410",
    department: "Operations",
    role: "Operations Manager",
    bank: "**** **** **** 5678",
    risk: "Ghost Employee",
    severity: "Critical",
    status: "flagged",
    icon: <AlertTriangle size={12} />,
  
  },
];